### PR TITLE
os flags for unix (for compiling on windows)

### PR DESCRIPTION
**Pull request by johnpmayer**
Compiles on windows (MSVC)

```
PS C:\Users\John\src\rotor-stream> rustc --version --verbose
rustc 1.7.0 (a5d1e7a59 2016-02-29)
binary: rustc
commit-hash: a5d1e7a59a2a3413c377b003075349f854304b5e
commit-date: 2016-02-29
host: x86_64-pc-windows-msvc
release: 1.7.0
```

### CODE REVIEW

**Comment by johnpmayer** [comment]
Hmm, maybe want to bump to 0.6.2 as well?

**Comment by tailhook** [comment]
Merged. Thanks!

You don't need version bump in pull request. We bump version in separate commit always. Do you need a release soon?

**Comment by johnpmayer** [comment]
I'm fine to pin to a revision in the short term, but now that this does fix
rotor-http as well.

**Comment by tailhook** [comment]
No problem. I've just pushed 0.6.2 (I don't have to update rotor-http as far as I understand, it should pick up new version by default, you may need to remove `Cargo.lock` sometimes, though)

**Pull request merged**
